config/routes.rb
SurkleApp::Application.routes.draw do
  get "surkles_users/add_user_to_surkle"
  get "surkles_users/remove_user_from_surkle"
  resources :project_products

  resources :companies

  resources :projects

  root to: "application#index"
  devise_for :users
  resources :iconups
  post '/iconups-products' => 'iconups#add_product_to_iconup'
  resources :users
  resources :icons
  resources :products
  resources :surkles

  

end

app/models/surkle.rb
class Surkle < ActiveRecord::Base
	has_many :iconups
	belongs_to :project
	has_many :users, through: :surkles_users

	has_attached_file :floorplan, :styles => {:thumb => "100x100>", :medium => "300X300>", :canvas => "960X600>"}, :default_url => "/images/floorplan/:style/missing.png"
	validates_attachment_content_type :floorplan, :content_type => %w(image/jpeg image/jpg image/png application/pdf document/pdf)
end

app/controllers/surkles_controller.rb
class SurklesController < ApplicationController
  before_action :set_surkle, only: [:show, :edit, :update, :destroy]

  # GET /surkles
  # GET /surkles.json
  def index
    @surkles = Surkle.all
  end

  # GET /surkles/1
  # GET /surkles/1.json
  def show
    @iconup = Iconup.new()
    @surkle.iconups
  end

  # GET /surkles/new
  def new
    @surkle = Surkle.new
  end

  # GET /surkles/1/edit
  def edit
  end

  # POST /surkles
  # POST /surkles.json
  def create
    @surkle = Surkle.create(surkle_params)
    SurklesUser.add_user_to_surkle(current_user.id, @surkle.id)
    

    respond_to do |format|
      if @surkle.save
        format.html { redirect_to @surkle, notice: 'Surkle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @surkle }
      else
        format.html { render action: 'new' }
        format.json { render json: @surkle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surkles/1
  # PATCH/PUT /surkles/1.json
  def update
    respond_to do |format|
      if @surkle.update(surkle_params)
        format.html { redirect_to @surkle, notice: 'Surkle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @surkle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surkles/1
  # DELETE /surkles/1.json
  def destroy
    @surkle.destroy
    respond_to do |format|
      format.html { redirect_to surkles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surkle
      @surkle = Surkle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surkle_params
      params.require(:surkle).permit(:floorplan, :description, :location, :timestamps)
    end
end

app/helpers/surkles_helper.rb
module SurklesHelper
end

app/views/surkles/_form.html.erb
<%= form_for @surkle, :html => { :multipart => true } do |f| %></%>
  <% if @surkle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@surkle.errors.count, "error") %> prohibited this surkle from being saved:</h2>

      <ul>
      <% @surkle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :floorplan %><br>
    <%= f.file_field :floorplan %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surkles/_surkle.html.erb
 <% surkles.each do |surkle| %>
      <%= link_to surkle do %>
      <tr>
        <td><%= image_tag( surkle.floorplan.url(:thumb)) %></td>
        <td><%= surkle.description %></td>
        <td><%= surkle.location %></td>
        <td><%= link_to 'Edit', edit_surkle_path(surkle) %></td>
        <td><%= link_to 'Destroy', surkle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>

app/views/surkles/edit.html.erb
<h1>Editing surkle</h1>

<%= render 'form' %>

<%= link_to 'Show', @surkle %> |
<%= link_to 'Back', surkles_path %>

app/views/surkles/index.html.erb
<h1>Listing surkles</h1>

<table>
  <thead>
    <tr>
      <th>Floorplan</th>
      <th>Description</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @surkles.each do |surkle| %>
      <tr>
        <td><%= image_tag( surkle.floorplan, width: "100px") %></td>
        <td><%= surkle.description %></td>
        <td><%= surkle.location %></td>
        <td><%= link_to 'Show', surkle %></td>
        <td><%= link_to 'Edit', edit_surkle_path(surkle) %></td>
        <td><%= link_to 'Destroy', surkle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Surkle', new_surkle_path %>

app/views/surkles/new.html.erb
<div class="row">
	<div class="large-4 colums right">
		<h1>New surkle</h1>

		<%= render 'form' %>

		<%= link_to 'Back', surkles_path %>
	</div>
</div>

app/views/surkles/show.html.erb
<div class="row">
	<div class="large-12 columns left">
	  <div class="row">
	  	<div class="large-6 columns left">
	  		<strong>Description:</strong>
			  <%= @surkle.description %>
	  	</div>
	  	<div class="large-6 columns right">
	  		<strong>Location:</strong>
			  <%= @surkle.location %>
	  	</div>
	  </div>
	  <div id="floorplan">
	  	<%= image_tag(@surkle.floorplan.url(:canvas)) %>
			<%= render @surkle.iconups %>
			<% @surkle.iconups.each do |iconup| %>
				<%= render partial: 'iconups/show', locals: {iconup: iconup} %>
			<% end %>

	  </div>
	</div>
</div>

<% set_of_pairs = [] %>

<% Product.all.each do |product| %>
	<% pair = ["#{product.name} - #{product.description}", product.id] %>
	<% set_of_pairs << pair %>
<% end %>


<div class="row">



	<div class="large-3 columns right border glow" id="new-iconup">
		<%= form_for(@iconup, remote: true) do |f| %>
		  <% if @iconup.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@iconup.errors.count, "error") %> prohibited this iconup from being saved:</h2>

		      <ul>
		      <% @iconup.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="field">
		    <input type="hidden" name="iconup[surkle_id]" value="<%= @surkle.id %>">
		  </div>
				
			<% icons = [] %>
		  <% Icon.all.each do |icon| %>
				<% icons << icon.image.url(:tiny) %>
		  <% end %>

		  <div class="field">
		    <%= f.label :icon_id %><br>
		    <%= f.text_field :icon_id %>
		  </div>
		  <div class="field">
		    <%= f.label :description %><br>
		    <%= f.text_field :description %>
		  </div>
		  <div class="field">
		    <%= f.label :notes %><br>
		    <%= f.text_area :notes %>
		  </div>
			
		  <div>
		  	<%= f.hidden_field(:x_coordinate) %>
		  </div>

		  <div>
		  	<%= f.hidden_field(:y_coordinate) %>
		  </div>

		  <div class="action">
		    <%= f.submit(class: "small button") %>
		  </div>
		<% end %>
	</div>
</div>

<%= link_to 'Edit', edit_surkle_path(@surkle) %> |
<%= link_to 'Back', surkles_path %>