config/routes.rb
SurkleApp::Application.routes.draw do
  get "surkles_users/add_user_to_surkle"
  get "surkles_users/remove_user_from_surkle"
  resources :project_products

  resources :companies

  resources :projects

  root to: "application#index"
  devise_for :users
  resources :iconups
  post '/iconups-products' => 'iconups#add_product_to_iconup'
  resources :users
  resources :icons
  resources :products
  resources :surkles

  

end

app/models/icon.rb
class Icon < ActiveRecord::Base
	has_many :iconups
	has_many :products, through: :iconups
	has_many :surkles, through: :iconups

	has_attached_file :image, :styles => {:tiny => "25x25>", :small => "50x50>", :thumb => "100x100" }, :default_url => "/images/floorplan/:style/missing.png"
	validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png image/gif)
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  before_action :set_icon, only: [:show, :edit, :update, :destroy]

  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
  end

  # GET /icons/new
  def new
    @icon = Icon.new
  end

  # GET /icons/1/edit
  def edit
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new(icon_params)

    respond_to do |format|
      if @icon.save
        format.html { redirect_to @icon, notice: 'Icon was successfully created.' }
        format.json { render action: 'show', status: :created, location: @icon }
      else
        format.html { render action: 'new' }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icons/1
  # PATCH/PUT /icons/1.json
  def update
    respond_to do |format|
      if @icon.update(icon_params)
        format.html { redirect_to @icon, notice: 'Icon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon.destroy
    respond_to do |format|
      format.html { redirect_to icons_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icon
      @icon = Icon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icon_params
      params.require(:icon).permit(:name, :image)
    end
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/icons/_form.html.erb
<%= form_for(@icon) do |f| %>
  <% if @icon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
      <% @icon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/icons/edit.html.erb
<h1>Editing icon</h1>

<%= render 'form' %>

<%= link_to 'Show', @icon %> |
<%= link_to 'Back', icons_path %>

app/views/icons/index.html.erb
<div class="row">
  <div class="large-4 columns">
    <h1>Listing icons</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Image</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @icons.each do |icon| %>
          <tr>
            <td><%= icon.name %></td>
            <td><%= image_tag icon.image, size: "50x50" %></td>
            <td><%= link_to 'Show', icon %></td>
            <td><%= link_to 'Edit', edit_icon_path(icon) %></td>
            <td><%= link_to 'Destroy', icon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Icon', new_icon_path %>
  </div>
</div>

app/views/icons/new.html.erb
<div class="row">
	<div class="large-4 columns right">
		<h1>New icon</h1>

		<%= render 'form' %>

		<%= link_to 'Back', icons_path %>
	</div>
</div>

app/views/icons/show.html.erb
<div class="row">
	<div class="large-6 columns">
		<p>
		  <strong>Name:</strong>
		  <%= @icon.name %>
		</p>

		<p>
		  <strong>Image:</strong>
		  <%= image_tag @icon.image.url(:original) %>
		</p>

		<%= link_to 'Edit', edit_icon_path(@icon) %> |
		<%= link_to 'Back', icons_path %>
	</div>
</div>